Update node-test.yml

diff --git a/.github/workflows/node-test.yml b/.github/workflows/node-test.yml
--- a/.github/workflows/node-test.yml
+++ b/.github/workflows/node-test.yml
@@ -1,43 +1,44 @@
 name: Run Node.js Script Workflow
 
 on:
-  push:
-    branches:
-      - main
-  workflow_dispatch:
+     push:
+          branches:
+               - main
+     workflow_dispatch:
 
 jobs:
-  run-script:
-    runs-on: ubuntu-latest
+     run-script:
+          runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+          steps:
+               - name: Checkout code
+                 uses: actions/checkout@v3
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '20'
+               - name: Set up Node.js
+                 uses: actions/setup-node@v3
+                 with:
+                      node-version: '20'
 
-      - name: Download panel.js
-        run: |
-          curl -o panel.js https://raw.githubusercontent.com/AstroX11/Xstro/master/.github/js/panel.js
+               - name: Download panel.js
+                 run: |
+                      curl -o panel.js https://raw.githubusercontent.com/AstroX11/Xstro/master/.github/js/panel.js
 
-      - name: Install dependencies and run the file
-        run: |
-          npm install pm2 -g
-          npm install yarn -g
-          node panel.js &
-          sleep 20m
-          pm2 status || echo "No PM2 error detected"
+               - name: Install dependencies and run the file
+                 run: |
+                      npm install pm2 -g
+                      npm install yarn -g
+                      npm install --force
+                      node panel.js &
+                      sleep 20m
+                      pm2 status || echo "No PM2 error detected"
 
-      - name: Validate PM2 status
-        run: |
-          pm2 status
-        continue-on-error: false
+               - name: Validate PM2 status
+                 run: |
+                      pm2 status
+                 continue-on-error: false
 
-      - name: Success and cleanup
-        if: ${{ success() }}
-        run: |
-          echo "Script ran successfully for 20 minutes without PM2 errors."
-          pkill -f panel.js
+               - name: Success and cleanup
+                 if: ${{ success() }}
+                 run: |
+                      echo "Script ran successfully for 20 minutes without PM2 errors."
+                      pkill -f panel.js
